version: "3.7"
services:
  jupyter:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter_spark_training
    volumes:
      - /Users/u004247/Documents/_GITHUB/Pyspark_Training/Notebooks:/home/jovyan/notebooks
      
    ports:
      - "8686:8888"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '1.00'
          memory: 1024M